[Fix] Fix onnx2ncnn.cpp bugs.
open-mmlab/mmdeploy pull request #1518
Opened 2022-12-12 09:19 UTC by hanrui1sensetime

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Fix some of onnx2ncnn.cpp bugs. Especially for `RTMPose` model deployment later.

## Modification

-[x] Fix `Gemm` for opset > 9, which is optional for the third input, while original onnx2ncnn needs the third input strictly.
-[x] Sync the `Reduction` op from the newest onnx2ncnn in [ncnn](https://github.com/Tencent/ncnn/blob/master/tools/onnx/onnx2ncnn.cpp) 

Other ops sync from the newest onnx2ncnn in [ncnn](https://github.com/Tencent/ncnn/blob/master/tools/onnx/onnx2ncnn.cpp) 
will be fixed later in another PR. This PR is mainly for `RTMPose` model.

## BC-breaking (Optional)

None.

## Use cases (Optional)

None.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

2022-12-14 02:31 UTC, RunningLeon reviewed
could add ut for this case

2022-12-14 12:48 UTC, lvhan028 commented
> could add ut for this case

It's `onnx2ncnn.cpp`, coming from ncnn repo. I think we don't need to add unit tests for it.

2022-12-15 06:27 UTC, RunningLeon approved these changes
LGTM

2022-12-16 06:49 UTC, tpoisonooo requested changes

2022-12-20 07:57 UTC, hanrui1sensetime commented on csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/onnx2ncnn.cpp
>          fprintf(pp, " -23303=%zu", axes.size());
> I have never seen any `gemm axes` existed in original onnx2ncnn https://github.com/Tencent/ncnn/blob/master/tools/onnx/onnx2ncnn.cpp

The code you have commented fix the `Reduction` node, not the `Gemm`. `Gemm` fix code are on the above.
The axes in `Reduction` node is from [here](https://github.com/Tencent/ncnn/blob/master/tools/onnx/onnx2ncnn.cpp#L5487), FYI.

2022-12-20 13:45 UTC, hanrui1sensetime commented on csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/onnx2ncnn.cpp
> +          if (axes[j] == 0 || axes[j] > 4 || axes[j] < -3)
> ncnn recently upgraded gemm opr for removing `if-else` conv kernel, please make sure that all fix would be compatible with new version.
> 
> check https://github.com/Tencent/ncnn/blob/master/src/layer/gemm.cpp

Newest ncnn gemm implementation will lead to seg fault for gemm x86 specific op, but seems like bugs on avx512 command. Now only can ensure the feature on ncnn version 20221128 works.

2022-12-29 04:10 UTC, tpoisonooo approved these changes

2022-12-29 04:14 UTC, merged